In [74]:
import pandas as pd

In [75]:
df = pd.read_csv("Output.dat", sep="\t", header=None)

In [76]:
result = []
for i in range(20):
    result.append(df.iloc[i::20].sum().tolist())

In [77]:
df = pd.DataFrame(result)
df.to_csv("ParsedOutputScaling.dat", sep="\t", header=False)
df

           0         1         2         3
0   2.134243  2.108099  2.105475  2.106442
1   1.947929  0.974557  0.975875  0.979642
2   2.045846  0.666411  0.642999  0.623382
3   1.890467  0.487318  0.482680  0.481701
4   1.960861  0.404709  0.394221  0.385338
5   1.948581  0.344814  0.344104  0.344764
6   2.000655  0.303792  0.287923  0.287377
7   1.921153  0.262669  0.262088  0.262117
8   1.950274  0.244235  0.242487  0.232251
9   1.997387  0.224854  0.224602  0.224901
10  2.052399  0.215275  0.214601  0.214812
11  2.135532  0.202750  0.201836  0.201849
12  1.967443  0.172188  0.171143  0.542265
13  2.025058  0.165569  0.164864  0.164903
14  2.054683  0.157477  0.156473  0.156555
15  2.032077  0.233906  0.159076  0.142374
16  2.021251  0.139894  0.137388  0.137323
17  2.047791  0.132122  0.129706  0.129766
18  1.964098  0.119954  0.118729  0.118756
19  1.997009  0.147766  0.144007  0.123730

In [78]:
# Speedup
df[df.columns[1]] = df[df.columns[0]]/df[df.columns[1]]
df[df.columns[2]] = df[df.columns[0]]/df[df.columns[2]]
df[df.columns[3]] = df[df.columns[0]]/df[df.columns[3]]
df

           0          1          2          3
0   2.134243   1.012402   1.013663   1.013198
1   1.947929   1.998784   1.996085   1.988409
2   2.045846   3.069946   3.181725   3.281850
3   1.890467   3.879329   3.916605   3.924565
4   1.960861   4.845113   4.974015   5.088678
5   1.948581   5.651108   5.662768   5.651927
6   2.000655   6.585608   6.948577   6.961778
7   1.921153   7.313969   7.330183   7.329372
8   1.950274   7.985236   8.042798   8.397268
9   1.997387   8.883040   8.893006   8.881183
10  2.052399   9.533847   9.563790   9.554396
11  2.135532  10.532834  10.580531  10.579849
12  1.967443  11.426133  11.495901   3.628195
13  2.025058  12.230901  12.283203  12.280298
14  2.054683  13.047512  13.131230  13.124352
15  2.032077   8.687580  12.774253  14.272810
16  2.021251  14.448447  14.711991  14.718955
17  2.047791  15.499243  15.787944  15.780644
18  1.964098  16.373760  16.542698  16.538937
19  1.997009  13.514672  13.867444  16.140055

In [79]:
df.to_csv("ParsedOutputSpeedup.dat", sep="\t", header=False)